### ISSUE TITLE
Incompatibility with awilix

### ISSUE THREAD

**Issue by sobrinho** [es-shims/es5-shim#480] opened 2022-03-09 00:57 UTC
Not sure how to investigate yet but adding the es5-shim breaks our app.

Removing it, it works again just fine.

The main issue here is that our client is using a widget from another vendor that includes the ES5 Shim, so, not easy just to ask to remove the widget or ask the vendor to do some fix.

But we are willing to fix that in our side, probably something is leaking into the browser and breaking it.

Any idea where to start?

**Comment by CircleTan** [comment] 2022-03-09 00:58
你的邮件我已收到了，谢谢。

**Comment by sobrinho** [comment] 2022-03-09 01:12
<img width="770" alt="Screen Shot 2022-03-08 at 22 11 15" src="https://user-images.githubusercontent.com/26460/157352966-2bf6dd8f-86df-49b6-a741-418f947f80ee.png">
<img width="267" alt="Screen Shot 2022-03-08 at 22 11 22" src="https://user-images.githubusercontent.com/26460/157352967-836e2ed6-06ec-48c6-af55-ca56b2dd6ba6.png">

Pinned the issue to spreading an object that without es5-shim does work.

**Comment by ljharb** [comment] 2022-03-09 01:54
Hmm - the “could not resolve” error doesn’t seem like it’s coming from es5-shim. What are you using to transpile object spread?

**Comment by sobrinho** [comment] 2022-03-09 22:00
The app was created with vue-cli. What info do you need?

**Comment by ljharb** [comment] 2022-03-09 22:03
I'm not familiar with vue projects. Do you get that error when running eslint, or when bundling (with webpack, i presume?), or at runtime?

**Comment by sobrinho** [comment] 2022-03-09 22:07
Let me build an example and get back to you.

**Comment by sobrinho** [comment] 2022-03-09 22:32
https://github.com/sobrinho/es5-shim-480

You can run `yarn run serve` and access `localhost:8080` and open the inspector.

If you remove the es5-shim from the public/index.html, it works just fine.

It is all standard files generated by `npx @vue-cli create example` and selected Vue2 and JS, added awilix, created a dummy container and then added es5-shim.

I don't think it is related to the Vue or Awilix itself, it is about something that Awilix is doing and Babel is trying to compile.

**Comment by ljharb** [comment] 2022-03-14 19:50
Note that this app crashes immediately in Safari, because `Error.captureStackTrace` is a nonstandard chrome-only API.

I can definitely reproduce this in Chrome, and will continue to look into the error. It's also possible it's coming from webpack 5, and I've asked them about it as well.

**Comment by ljharb** [comment] 2022-03-15 16:55
ok, so there's a few issues. For one, you're using an out of date version of es5-shim, plus you're pulling it off a CDN instead of bundling it.

Second, the app is already using core-js, and while core-js should work fine in concert with es-shims, you shouldn't need both - i believe core-js provides everything es5-shim does.

Third, es5-shim isn't meant to be used alone; it's meant to be used in concert with the es6-shim - but adding that to the HTML file doesn't fix it.

The actual problem is caused by something doing `require(Symbol.toStringTag)`, but i'm not sure why it would be doing that. The exception is thrown when `__webpack_require__` is called, trying to load `babel-loader`. I'm also not sure why babel would be running in the browser at all - but awilix is requiring it, it seems (i'd file an issue about that; babel's not meant to be used in the browser).

I suspect the problem is that one of the methods es5-shim patches is producing a Symbol, and some code inside babel-loader - or that babel-loader is processing - may not be expecting that.

**Comment by sobrinho** [comment] 2022-03-15 20:44
> Third, es5-shim isn't meant to be used alone; it's meant to be used in concert with the es6-shim - but adding that to the HTML file doesn't fix it.

The problem is that we don't control where our widget is used.

So, a customer have the es5-shim in their website and the widget does not work there.

**Comment by ljharb** [comment] 2022-03-15 20:53
thanks, that's useful context. the customer is the one using awilix?

**Comment by sobrinho** [comment] 2022-03-15 21:17
Nope, I am the one using it. The customer is the one using es5-shim in their website.

**Comment by ljharb** [comment] 2022-03-15 22:29
Have you filed this with awilix? Their code looks pretty complex, so they can probably find their dynamic requires faster than i can.

**Comment by sobrinho** [comment] 2022-03-16 16:48
Yep! https://github.com/jeffijoe/awilix/issues/286

**Comment by ljharb** [comment] 2022-03-16 18:24
Looks like https://github.com/jeffijoe/awilix/pull/287 will fix it, so I'll close this :-)

**Closed by ljharb** 2022-03-16 18:24 UTC

**Comment by CircleTan** [comment] 2022-10-11 07:23
你的邮件我已收到了，谢谢。
