### ISSUE TITLE
[Proposal] Split Shims

### ISSUE THREAD

**Issue by garygreen** [es-shims/es5-shim#276] opened 2014-10-30 18:49 UTC
At the moment there is one big file (es5-shim.js) it would be good to split this into different files based on the type of shim. The benefit of this would be that you could use a build tool to only shim the functionality that you need. So if you needed just the array based shims, but don't want to carry the full weight of the module, you can just include array.js.

### Proposed structure

	/shims
		array.js
			[every, filter, forEach, indexOf, lastIndexOf, map, some, reduce, reduceRight, isArray]
		date.js
			[now, toJSON, parse, toISOString]
		bind.js
			[bind]
		number.js
			[toFixed, parseInt]
		object.js
			[keys]
		string.js
			[split, trim, replace]

**Comment by ljharb** [comment] 2015-01-08 00:30
Please see the design of https://github.com/es-shims/es7-shim/ as an example of where I'd eventually like to take the `es6-shim`. You can do `require('es7-shim')`, or `require('es7-shim/Array')` or `require('es7-shim/Array.prototype')` or `require('es7-shim/Array.prototype.includes')` - all of which will have a `.shim()` method that installs it on the global object. In addition, each shim in the `es7-shim` is an independent module on `npm` that you can include independently. The shim also has a browserify entry point, so any browserification of the whole shim will automatically call the `.shim()` method.

**Comment by davidtheclark** [comment] 2015-01-13 01:32
That sounds like a very good approach. Resembles `lodash-node`, which I think is perfect for a frontend browserified workflow.

**Comment by viperdezigns** [comment] 2015-03-16 19:13
+1 to this

Keeping this bower component up to date with master is going to be a pain while cherry picking only what I need.

**Comment by cmawhorter** [comment] 2015-03-17 16:36
@ljharb Sounds beautiful.  

@viperdezigns submodules and symlinks for now

**Comment by ljharb** [comment] 2015-06-21 07:48
Closing as a duplicate of #175

**Closed by ljharb** 2015-06-21 07:48 UTC
