### ISSUE TITLE
es5-sham: Object.defineProperties + constructor in IE 8

### ISSUE THREAD

**Issue by lukescott** [es-shims/es5-shim#292] opened 2015-02-10 09:44 UTC
This doesn't work in IE 8:
```javascript
Object.defineProperties(obj, {
    constructor: {
        value: subClass,
        enumerable: false,
        writable: true,
        configurable: true
    }
});
````
Reason being that a for in loop is used. This works in core-js, another ES5 shim/sham.

**Comment by ljharb** [comment] 2015-02-10 09:53
This looks like a duplicate of #289.

**Closed by ljharb** 2015-02-10 09:53 UTC
Labels: ES5 sham
